### PR TITLE
add custom logging support

### PR DESCRIPTION
**Pull request by jagheterfredrik**
@sp-ac @vzctl @daenney

### CODE REVIEW

**Comment by acotenoff** [comment]
Looks great +1

**Comment by daenney** [comment]
_sigh_ Something in the Ruby ecosystem is broken again. I'll see if I can figure out where this is blowing up but you might have to rebase once I get that fixed.

**Comment by jagheterfredrik** [comment]
Haha, ok @daenney, thanks for poking around for us!

**Comment by jagheterfredrik** [comment]
Blocked on https://github.com/spotify/puppet-talos/pull/2

**Comment by daenney** [comment]
I merged #2 after realising I was being an idiot. could you rebase?

**Comment by jagheterfredrik** [comment]
Done! Thanks @daenney

**Pull request merged**
